version: '3'

services:
  django_gunicorn:
    build: .
    # command: gunicorn unicon.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 unicon.wsgi --workers=4
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

