# Generated by Django 4.1.6 on 2023-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationServiceContentViewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=255)),
                ('content', models.ManyToManyField(related_name='content_views_count', to='main.informationservice')),
            ],
        ),
    ]
