# Generated by Django 4.1.6 on 2023-02-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_informationservicecontentviewsmodel_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationservicecontentviewsmodel',
            name='info_view_cat',
            field=models.CharField(choices=[('NS', 'YANGILIKLAR'), ('PR', 'FOTO REPORTAJ'), ('VR', 'VIDEO REPORTAJ')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
