# Generated by Django 4.1.6 on 2023-02-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_informationservicecontentviewsmodel_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationservicecontentviewsmodel',
            name='info_view_cat',
        ),
    ]
