# Generated by Django 4.1.6 on 2023-02-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_emailmessages_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
    ]
