# Generated by Django 4.1.6 on 2023-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_0012_merge_20230213_1851_0012_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
    ]
