# Generated by Django 4.1.6 on 2023-02-15 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_services_img_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAdditionalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content/content-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])),
                ('is_video', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'YANGILIKLAR'), ('PR', 'FOTO REPORTAJ'), ('VR', 'VIDEO REPORTAJ'), ('MM', 'MEMORANDUM'), ('oav', 'OAV_ABOUT_US')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ContentImages',
        ),
        migrations.AddField(
            model_name='contentadditionalfiles',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='main.informationservice'),
        ),
    ]
