# Generated by Django 4.1.6 on 2023-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_contactus_created_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessages',
            name='created_add',
            field=models.DateField(auto_now_add=True),
        ),
    ]
