# Generated by Django 4.1.6 on 2023-02-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_emailmessages_created_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='emailmessages',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
