# Generated by Django 4.1.6 on 2023-02-16 05:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_created_add_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationServiceWithVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_cat', models.CharField(choices=[('VR', 'VIDEO REPORTAJ'), ('oav', 'OAV_ABOUT_US')], max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Axborat xizmati',
                'verbose_name_plural': 'Axborat xizmatlari Video',
            },
        ),
        migrations.AlterField(
            model_name='contentadditionalfiles',
            name='file',
            field=models.ImageField(upload_to='content/content-photo-files'),
        ),
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'YANGILIKLAR'), ('PR', 'FOTO REPORTAJ'), ('MM', 'MEMORANDUM')], max_length=2),
        ),
        migrations.CreateModel(
            name='InformationServiceContentVideoViewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=255)),
                ('content', models.ManyToManyField(related_name='content_views_count', to='main.informationservicewithvideo')),
            ],
        ),
        migrations.CreateModel(
            name='ContentAdditionalFilesForVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content/content-video-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='main.informationservicewithvideo')),
            ],
        ),
    ]
