# Generated by Django 4.1.6 on 2023-02-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_informationservicewithvideo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentadditionalfiles',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='contentadditionalfilesforvideo',
            old_name='file',
            new_name='video',
        ),
    ]
