# Generated by Django 4.1.6 on 2023-02-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_informationservicecontentvideoviewsmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationservice',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentadditionalfiles',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='main.informationservice'),
        ),
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'NEWS'), ('PR', 'PHOTO REPORT'), ('MM', 'MEMORANDUM'), ('oav', 'OAV ABOUT US'), ('VR', 'VIDEO REPORT')], max_length=3),
        ),
        migrations.DeleteModel(
            name='InformationServiceContentViewsModel',
        ),
    ]
