# Generated by Django 4.1.6 on 2023-02-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_informationservice_views_count_and_more'),
        ('main', '0028_alter_informationservice_info_cat'),
    ]

    operations = [
    ]
