# Generated by Django 4.1.6 on 2023-02-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_modul_delete_product'),
        ('main', '0029_merge_20230216_1635'),
    ]

    operations = [
    ]
