# Generated by Django 4.1.6 on 2023-02-06 06:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
