# Generated by Django 4.1.6 on 2023-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_informationservicecontentviewsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationservicecontentviewsmodel',
            name='mac_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
