# Generated by Django 4.1.6 on 2023-02-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_content_content_alter_subcategories_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='file-message/content-images')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='main.content')),
            ],
        ),
    ]
