# Generated by Django 4.1.6 on 2023-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_informationservicecontentviewsmodel_info_view_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationservicecontentviewsmodel',
            name='mac_address',
            field=models.CharField(max_length=255),
        ),
    ]
