# Generated by Django 4.1.6 on 2023-02-06 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contentimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
