# Generated by Django 4.1.6 on 2023-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_content_content_ru_content_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('RT', 'RAXBARIYAT'), ('IK', 'ILMIY KENGASH'), ('BJ', 'BIZNING JAMOA')], max_length=2)),
                ('image', models.ImageField(upload_to='content/member-image')),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='emailmessages',
            options={'verbose_name_plural': 'Email messages'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name_plural': 'Sub categories'},
        ),
    ]
