# Generated by Django 4.1.6 on 2023-02-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_informationservicecontentviewsmodel_info_view_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessages',
            name='is_agree',
        ),
    ]
