# Generated by Django 4.1.6 on 2023-02-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutus_members_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
    ]
