# Generated by Django 4.1.6 on 2023-02-07 06:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_members_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_status', models.CharField(choices=[('CS', 'KONKURSLAR'), ('IK', 'TAKLIFLAR_TANLOVI')], max_length=2)),
                ('status_type', models.CharField(choices=[('CS', 'OZ_KUCHIDA'), ('IK', 'MUDDATI_TUGAGAN')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='content/nav-about-product-icon')),
                ('img', models.ImageField(blank=True, null=True, upload_to='content/nav-about-product-img')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='content/nav-about-resource-icon')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='content/resource-content-file')),
                ('date', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_content', to='main.resource')),
            ],
        ),
    ]
