# Generated by Django 4.1.6 on 2023-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_announcement_product_resource_resourcecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='short_desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
