# Generated by Django 4.1.6 on 2023-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactus_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'YANGILIKLAR'), ('PR', 'FOTO REPORTAJ'), ('VR', 'VIDEO REPORTAJ'), ('MM', 'MEMORANDUM')], max_length=2),
        ),
    ]
