# Generated by Django 4.1.6 on 2023-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resource_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecontent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
