# Generated by Django 4.1.6 on 2023-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_partners_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessages',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='emailmessages',
            name='name_organization',
        ),
        migrations.RemoveField(
            model_name='emailmessages',
            name='title',
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='FISH or Name organization'),
            preserve_default=False,
        ),
    ]
