# Generated by Django 4.1.6 on 2023-02-13 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_emailmessages_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AddField(
            model_name='members',
            name='workday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='workday_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='workday_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
