# Generated by Django 4.1.6 on 2023-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_options_alter_services_options'),
        ('main', '0011_alter_product_options_alter_services_options_and_more'),
    ]

    operations = [
    ]
