# Generated by Django 4.1.6 on 2023-02-07 13:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_services_delete_aboutus_alter_emailmessages_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_cat', models.CharField(choices=[('NS', 'YANGILIKLAR'), ('AU', 'UNICON.UZ HAQIDA'), ('PR', 'FOTO REPORTAJ'), ('VR', 'VIDEO REPORTAJ'), ('OA', 'OAV BIZ HAQIMIZDA')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Axborat xizmati',
                'verbose_name_plural': 'Axborat xizmatlari',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
        migrations.AlterModelOptions(
            name='emailmessages',
            options={'verbose_name': 'Email xabari', 'verbose_name_plural': 'Email xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resurs', 'verbose_name_plural': 'Resurslar'},
        ),
        migrations.AlterModelOptions(
            name='resourcecontent',
            options={'verbose_name': 'Resurs conteni', 'verbose_name_plural': 'Resurs contentlari'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
        migrations.AlterField(
            model_name='contentimages',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='main.informationservice'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
