# Generated by Django 4.1.6 on 2023-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_informationservice_remove_content_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'YANGILIKLAR'), ('PR', 'FOTO REPORTAJ'), ('VR', 'VIDEO REPORTAJ')], max_length=2),
        ),
    ]
