# Generated by Django 4.1.6 on 2023-02-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20230213_1851'),
        ('main', '0012_statistics'),
    ]

    operations = [
    ]
