# Generated by Django 4.1.6 on 2023-02-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_statistics_options'),
        ('main', '0014_alter_statistics_options'),
    ]

    operations = [
    ]
