# Generated by Django 4.1.6 on 2023-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20230215_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(default=' ', upload_to='content/services-icons'),
            preserve_default=False,
        ),
    ]
