# Generated by Django 4.1.6 on 2023-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='img',
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(default='', help_text='icon', upload_to='content/services-icons'),
            preserve_default=False,
        ),
    ]
