# Generated by Django 4.1.6 on 2023-02-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contentadditionalfiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentadditionalfiles',
            name='is_video',
        ),
    ]
