# Generated by Django 4.1.6 on 2023-02-16 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_file_contentadditionalfiles_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationservicecontentvideoviewsmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentadditionalfiles',
            name='image',
        ),
        migrations.AddField(
            model_name='contentadditionalfiles',
            name='file',
            field=models.FileField(default='', upload_to='content/content-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'mp4'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'news'), ('PR', 'PHOTO REPORT'), ('MM', 'MEMORANDUM'), ('oav', 'OAV ABOUT US'), ('VR', 'VIDEO REPORT')], max_length=3),
        ),
        migrations.DeleteModel(
            name='ContentAdditionalFilesForVideo',
        ),
        migrations.DeleteModel(
            name='InformationServiceContentVideoViewsModel',
        ),
        migrations.DeleteModel(
            name='InformationServiceWithVideo',
        ),
    ]
