# Generated by Django 4.1.6 on 2023-02-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_informationservicecontentvideoviewsmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentadditionalfiles',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='main.informationservice'),
        ),
    ]
