# Generated by Django 4.1.6 on 2023-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_contentadditionalfiles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'NEWS'), ('PR', 'PHOTO REPORT'), ('MM', 'MEMORANDUM'), ('oav', 'OAV ABOUT US'), ('VR', 'VIDEO REPORT')], max_length=3),
        ),
    ]
