# Generated by Django 4.1.6 on 2023-02-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_informationservice_views_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_register_number', models.CharField(max_length=255)),
                ('valid_status', models.CharField(choices=[('ACTING', 'ACTING')], max_length=6)),
                ('name_of_the_legal_entity', models.TextField()),
                ('itn', models.CharField(max_length=50)),
                ('legal_entity_address', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('web_site', models.URLField()),
                ('full_name_head_of_accretion_body', models.CharField(max_length=255)),
                ('accreditation_object_address', models.TextField()),
                ('accreditation_date', models.DateTimeField()),
                ('link_to_the_scope_of_accreditation', models.FileField(upload_to='content/module-file')),
                ('certificate_of_accreditation', models.FileField(upload_to='content/module-file')),
                ('type_of_accreditation_object', models.CharField(max_length=255)),
                ('status_date', models.DateTimeField()),
                ('validity_period_of_the_accreditation_certificate', models.DateTimeField()),
                ('standard', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
