# Generated by Django 4.1.6 on 2023-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_informationservice_info_cat_alter_modul_itn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationservice',
            name='info_cat',
            field=models.CharField(choices=[('NS', 'NEWS'), ('PR', 'PHOTO REPORT'), ('MM', 'MEMORANDUM'), ('OU', 'OAV ABOUT US'), ('VR', 'VIDEO REPORT')], max_length=2, verbose_name='category'),
        ),
    ]
