# Generated by Django 4.1.6 on 2023-02-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_informationservice_info_cat'),
        ('main', '0032_moduladditionalfiles'),
    ]

    operations = [
    ]
