# Generated by Django 4.1.6 on 2023-02-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_merge_20230222_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='content/module-file'),
        ),
        migrations.AddField(
            model_name='modul',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='content/module-file'),
        ),
        migrations.AddField(
            model_name='modul',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='content/module-file'),
        ),
        migrations.DeleteModel(
            name='ModulAdditionalFiles',
        ),
    ]
