# Generated by Django 4.1.6 on 2023-03-14 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_modul_file1_modul_file2_modul_file3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentadditionalfiles',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='video url/link'),
        ),
        migrations.AlterField(
            model_name='contentadditionalfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/content-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
