# Generated by Django 4.1.6 on 2023-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_contentadditionalfiles_video_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMessages',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
